apiVersion: v1
kind: Pod
metadata:
  name: netshoot
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["/bin/bash"]
      args: ["-c", "while true; do ping 172.30.227.43; sleep 60;done"]

